jobs:
  include:
    - stage: test
      name: Test Go
      language: go
      sudo: false
      go:
      - "1.13"
      script:
        go test -v ./... -cover
#    - name: Test Node
#      language: node_js
#      node_js:
#      - "10"
#      install:
#      - npm ci
#      script:
#      - npm t
