import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { Container, Typography, Box } from '@material-ui/core'
import { makeStyles } from '@material-ui/core/styles'
import Image from 'next/image'
import logo from '../../public/logo.png'
import HomePage from '../../src/components/HomePage'

const useStyles = makeStyles((theme) => ({
    logo: {
        position: 'relative',
        top: '10px',
        height: '64px',
        width: '64px',
        paddingRight: '16px',
    },
    header: {
        marginTop: '32px',
        marginBottom: '32px',
        display: 'flex',
        alignItems: 'center',
    },
    wrapper: {
        marginLeft: '40px',
        display: 'inline-block',
    },
    homeLink: {
        textDecoration: 'none',
        color: theme.palette.text.primary,
    },
}))

const Home: NextPage = () => {
    const classes = useStyles()

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta content="Generated by create next app" name="description" />
                <link href="/favicon.ico" rel="icon" />
            </Head>

            <main>
                <Container>
                    <Box className={classes.header}>
                        <Box className={classes.wrapper}>
                            <Link href="/">
                                <a className={classes.homeLink}>
                                    <Image alt="LoL Mastery Chest Viewer" className={classes.logo} src={logo} />
                                    <Typography component="h1" display="inline" variant="h2">
                                        LoL Mastery Chest Viewer
                                    </Typography>
                                </a>
                            </Link>
                        </Box>
                    </Box>
                    <HomePage />
                </Container>
            </main>
        </div>
    )
}

export default Home
